import type { OfficialSalary } from "@/types/salary"

export function getDemoSalaries(): OfficialSalary[] {
  return [
    {
      id: "sal-madrid-1",
      municipalityId: "m-madrid",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 105_422,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración. Sustituir por importación oficial ISPA.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-madrid-2",
      municipalityId: "m-madrid",
      year: 2023,
      personName: null,
      role: "Concejal/a con dedicación exclusiva",
      dedicationType: "exclusiva",
      grossAnnualAmount: 82_600,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración. Retribución media estimada de concejales con dedicación exclusiva.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-barcelona-1",
      municipalityId: "m-barcelona",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 100_786,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-barcelona-2",
      municipalityId: "m-barcelona",
      year: 2023,
      personName: null,
      role: "Concejal/a con dedicación exclusiva",
      dedicationType: "exclusiva",
      grossAnnualAmount: 78_450,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-valencia-1",
      municipalityId: "m-valencia",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 89_300,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-valencia-2",
      municipalityId: "m-valencia",
      year: 2023,
      personName: null,
      role: "Concejal/a con dedicación exclusiva",
      dedicationType: "exclusiva",
      grossAnnualAmount: 68_200,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-sevilla-1",
      municipalityId: "m-sevilla",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 85_200,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-zaragoza-1",
      municipalityId: "m-zaragoza",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 78_900,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-malaga-1",
      municipalityId: "m-malaga",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 82_400,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-valladolid-1",
      municipalityId: "m-valladolid",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 68_500,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-vigo-1",
      municipalityId: "m-vigo",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 72_100,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-alcobendas-1",
      municipalityId: "m-alcobendas",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 62_800,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-caravaca-1",
      municipalityId: "m-caravaca",
      year: 2023,
      personName: null,
      role: "Alcalde/Alcaldesa",
      dedicationType: "exclusiva",
      grossAnnualAmount: 42_500,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
    {
      id: "sal-caravaca-2",
      municipalityId: "m-caravaca",
      year: 2023,
      personName: null,
      role: "Concejal/a con dedicación parcial",
      dedicationType: "parcial",
      grossAnnualAmount: 18_200,
      sourceId: null,
      sourceFile: "demo-seed",
      notes: "Dato de demostración.",
      isDemo: true,
      createdAt: "2024-01-15T10:00:00Z",
    },
  ]
}
